# -*- coding: utf-8 -*-
"""Copy of task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kU3fFlpcubg6Ypw4_vSpxaXw2wEoGBua
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# Step 1: Create and connect to the database
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Step 2: Create a sales table (if not exists) and insert sample data
cursor.execute('''
    CREATE TABLE IF NOT EXISTS sales (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        product TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        price REAL NOT NULL
    )
''')

# Insert some sample data (only if table is empty)
cursor.execute("SELECT COUNT(*) FROM sales")
if cursor.fetchone()[0] == 0:
    sample_data = [
        ('Apples', 10, 0.5),
        ('Oranges', 5, 0.7),
        ('Bananas', 8, 0.3),
        ('Apples', 15, 0.5),
        ('Oranges', 10, 0.7),
        ('Bananas', 12, 0.3)
    ]
    cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)
    conn.commit()

# Step 3: Run SQL query to get total quantity and revenue per product
query = '''
    SELECT product,
           SUM(quantity) AS total_qty,
           SUM(quantity * price) AS revenue
    FROM sales
    GROUP BY product
'''
df = pd.read_sql_query(query, conn)

# Step 4: Display results using print
print("Sales Summary:")
print(df)

# Step 5: Plot revenue as a bar chart
df.plot(kind='bar', x='product', y='revenue', legend=False, color='skyblue')
plt.title("Total Revenue by Product")
plt.ylabel("Revenue ($)")
plt.xlabel("Product")
plt.tight_layout()
plt.savefig("sales_chart.png")
plt.show()

# Close the database connection
conn.close()